"""
Data Collector for GRPO Training
=================================
Downloads AI-generated text from public HuggingFace datasets.
These become the prompts for the humanizer model:
  Input:  AI-generated text
  Output: humanized version (generated by our policy)
  Reward: Copyleaks human probability

Primary source: Hello-SimpleAI/HC3 (ChatGPT answers vs human answers).
We take the ChatGPT answers as the "AI text" to humanize.
"""

import os
import re
import random
import logging
from typing import List, Iterator
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class TrainingSample:
    text: str           # AI-generated text (model input)
    source: str         # Dataset it came from
    original_id: str    # For deduplication


def _clean_text(text: str) -> str:
    """Basic cleaning: collapse whitespace, fix encoding artifacts."""
    text = re.sub(r"\s+", " ", text)
    text = text.replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2014", " - ").replace("\u2013", "-")
    return text.strip()


def load_hc3_dataset(
    split: str = "train",
    cache_dir: str = "./data_cache",
    min_chars: int = 200,
    max_chars: int = 2500,
    seed: int = 42,
) -> List[TrainingSample]:
    """
    Load ChatGPT answers from the HC3 dataset.
    HC3 = Human ChatGPT Comparison Corpus.
    Each row has 'chatgpt_answers' (list of strings) and 'human_answers'.
    We use chatgpt_answers as training inputs.
    """
    try:
        from datasets import load_dataset
    except ImportError:
        raise ImportError("Run: pip install datasets")

    logger.info("Downloading Hello-SimpleAI/HC3 (English subset)...")
    try:
        ds = load_dataset(
            "Hello-SimpleAI/HC3",
            "all",
            split=split,
            cache_dir=cache_dir,
            trust_remote_code=True,
        )
    except Exception as e:
        logger.warning(f"HC3 'all' failed ({e}), trying without config...")
        ds = load_dataset(
            "Hello-SimpleAI/HC3",
            split=split,
            cache_dir=cache_dir,
            trust_remote_code=True,
        )

    samples = []
    rng = random.Random(seed)

    for idx, row in enumerate(ds):
        answers = row.get("chatgpt_answers") or []
        if isinstance(answers, str):
            answers = [answers]
        for ans in answers:
            if not ans:
                continue
            text = _clean_text(ans)
            if min_chars <= len(text) <= max_chars:
                samples.append(TrainingSample(
                    text=text,
                    source="HC3",
                    original_id=f"hc3_{idx}",
                ))

    rng.shuffle(samples)
    logger.info(f"HC3: loaded {len(samples)} ChatGPT answer samples")
    return samples


def load_all_datasets(
    dataset_names: List[str],
    cache_dir: str = "./data_cache",
    min_chars: int = 200,
    max_chars: int = 2500,
    seed: int = 42,
) -> List[TrainingSample]:
    """Load and merge all configured datasets."""
    all_samples: List[TrainingSample] = []

    for name in dataset_names:
        if "HC3" in name or "hc3" in name:
            samples = load_hc3_dataset(
                cache_dir=cache_dir,
                min_chars=min_chars,
                max_chars=max_chars,
                seed=seed,
            )
            all_samples.extend(samples)
        else:
            logger.warning(f"Unknown dataset: {name}, skipping.")

    # Deduplicate by text prefix
    seen = set()
    deduped = []
    for s in all_samples:
        key = s.text[:100]
        if key not in seen:
            seen.add(key)
            deduped.append(s)

    rng = random.Random(seed)
    rng.shuffle(deduped)

    logger.info(f"Total training samples after dedup: {len(deduped)}")
    return deduped


class InfiniteDataLoader:
    """
    Cycles through samples infinitely, re-shuffling each epoch.
    Used by the GRPO trainer to sample prompts indefinitely.
    """

    def __init__(self, samples: List[TrainingSample], seed: int = 42):
        self.samples = list(samples)
        self.rng = random.Random(seed)
        self._idx = 0
        self._epoch = 0

    def next_batch(self, batch_size: int) -> List[TrainingSample]:
        batch = []
        while len(batch) < batch_size:
            if self._idx >= len(self.samples):
                self.rng.shuffle(self.samples)
                self._idx = 0
                self._epoch += 1
                logger.info(f"Data epoch {self._epoch}")
            batch.append(self.samples[self._idx])
            self._idx += 1
        return batch


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    samples = load_all_datasets(["Hello-SimpleAI/HC3"])
    print(f"Loaded {len(samples)} samples")
    print("\nFirst sample:")
    print(f"  Source: {samples[0].source}")
    print(f"  Length: {len(samples[0].text)} chars")
    print(f"  Text preview: {samples[0].text[:200]}...")
