"""
Data Collector for GRPO Training
=================================
Downloads AI-generated text from public HuggingFace datasets.
These become the prompts for the humanizer model:
  Input:  AI-generated text
  Output: humanized version (generated by our policy)
  Reward: Copyleaks human probability

Primary source: Hello-SimpleAI/HC3 (ChatGPT answers vs human answers).
We take the ChatGPT answers as the "AI text" to humanize.
"""

import os
import re
import random
import logging
from typing import List, Iterator
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class TrainingSample:
    text: str           # AI-generated text (model input)
    source: str         # Dataset it came from
    original_id: str    # For deduplication


def _clean_text(text: str) -> str:
    """Basic cleaning: collapse whitespace, fix encoding artifacts."""
    text = re.sub(r"\s+", " ", text)
    text = text.replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2014", " - ").replace("\u2013", "-")
    return text.strip()


def load_hc3_dataset(
    cache_dir: str = "./data_cache",
    min_chars: int = 200,
    max_chars: int = 2500,
    seed: int = 42,
) -> List[TrainingSample]:
    """
    Load ChatGPT answers from HC3 by downloading the JSONL directly.
    HC3's custom loading script is no longer supported by newer datasets
    versions, so we bypass it entirely and fetch the raw file.
    """
    import gzip
    import json
    import urllib.request
    from pathlib import Path

    os.makedirs(cache_dir, exist_ok=True)
    cache_path = Path(cache_dir) / "hc3_all.jsonl.gz"

    if not cache_path.exists():
        url = (
            "https://huggingface.co/datasets/Hello-SimpleAI/HC3"
            "/resolve/main/all.jsonl.gz"
        )
        logger.info(f"Downloading HC3 from {url} ...")
        urllib.request.urlretrieve(url, cache_path)
        logger.info(f"Saved to {cache_path}")

    samples = []
    rng = random.Random(seed)

    logger.info("Parsing HC3 JSONL...")
    with gzip.open(cache_path, "rt", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue

            answers = row.get("chatgpt_answers") or []
            if isinstance(answers, str):
                answers = [answers]
            for ans in answers:
                if not ans:
                    continue
                text = _clean_text(ans)
                if min_chars <= len(text) <= max_chars:
                    samples.append(TrainingSample(
                        text=text,
                        source="HC3",
                        original_id=f"hc3_{idx}",
                    ))

    rng.shuffle(samples)
    logger.info(f"HC3: loaded {len(samples)} ChatGPT answer samples")
    return samples


def load_alpaca_dataset(
    cache_dir: str = "./data_cache",
    min_chars: int = 200,
    max_chars: int = 2500,
    seed: int = 42,
) -> List[TrainingSample]:
    """
    Fallback dataset: Alpaca (GPT-3.5 instruction-following outputs).
    Concatenates instruction + output as the AI text to humanize.
    """
    try:
        from datasets import load_dataset
    except ImportError:
        raise ImportError("Run: pip install datasets")

    logger.info("Downloading tatsu-lab/alpaca (GPT-3.5 outputs)...")
    ds = load_dataset("tatsu-lab/alpaca", split="train", cache_dir=cache_dir)

    samples = []
    rng = random.Random(seed)

    for idx, row in enumerate(ds):
        # Combine instruction + output into a self-contained AI-written paragraph
        instruction = (row.get("instruction") or "").strip()
        output = (row.get("output") or "").strip()
        if not output:
            continue
        # Only take rows with paragraph-style outputs (not bullet lists/code)
        if output.startswith("-") or output.startswith("#") or "```" in output:
            continue
        text = _clean_text(f"{output}")
        if min_chars <= len(text) <= max_chars:
            samples.append(TrainingSample(
                text=text,
                source="Alpaca",
                original_id=f"alpaca_{idx}",
            ))

    rng.shuffle(samples)
    logger.info(f"Alpaca: loaded {len(samples)} GPT-3.5 output samples")
    return samples


def load_all_datasets(
    dataset_names: List[str],
    cache_dir: str = "./data_cache",
    min_chars: int = 200,
    max_chars: int = 2500,
    seed: int = 42,
) -> List[TrainingSample]:
    """Load and merge all configured datasets."""
    all_samples: List[TrainingSample] = []

    for name in dataset_names:
        if "HC3" in name or "hc3" in name:
            try:
                samples = load_hc3_dataset(
                    cache_dir=cache_dir,
                    min_chars=min_chars,
                    max_chars=max_chars,
                    seed=seed,
                )
                all_samples.extend(samples)
            except Exception as e:
                logger.warning(f"HC3 failed ({e}), falling back to Alpaca dataset.")
                samples = load_alpaca_dataset(
                    cache_dir=cache_dir,
                    min_chars=min_chars,
                    max_chars=max_chars,
                    seed=seed,
                )
                all_samples.extend(samples)
        elif "alpaca" in name.lower():
            samples = load_alpaca_dataset(
                cache_dir=cache_dir,
                min_chars=min_chars,
                max_chars=max_chars,
                seed=seed,
            )
            all_samples.extend(samples)
        else:
            logger.warning(f"Unknown dataset: {name}, skipping.")

    # Deduplicate by text prefix
    seen = set()
    deduped = []
    for s in all_samples:
        key = s.text[:100]
        if key not in seen:
            seen.add(key)
            deduped.append(s)

    rng = random.Random(seed)
    rng.shuffle(deduped)

    logger.info(f"Total training samples after dedup: {len(deduped)}")
    return deduped


class InfiniteDataLoader:
    """
    Cycles through samples infinitely, re-shuffling each epoch.
    Used by the GRPO trainer to sample prompts indefinitely.
    """

    def __init__(self, samples: List[TrainingSample], seed: int = 42):
        self.samples = list(samples)
        self.rng = random.Random(seed)
        self._idx = 0
        self._epoch = 0

    def next_batch(self, batch_size: int) -> List[TrainingSample]:
        batch = []
        while len(batch) < batch_size:
            if self._idx >= len(self.samples):
                self.rng.shuffle(self.samples)
                self._idx = 0
                self._epoch += 1
                logger.info(f"Data epoch {self._epoch}")
            batch.append(self.samples[self._idx])
            self._idx += 1
        return batch


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    samples = load_all_datasets(["Hello-SimpleAI/HC3"])
    print(f"Loaded {len(samples)} samples")
    print("\nFirst sample:")
    print(f"  Source: {samples[0].source}")
    print(f"  Length: {len(samples[0].text)} chars")
    print(f"  Text preview: {samples[0].text[:200]}...")
